# -*- coding: utf-8 -*-
"""RAG_With_Pdf_latest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glh1ldFVnjET8hfZhBdzdyVIcAeNw3XA
"""

#!pip install langchain
#!pip install langchain_community
#!pip install langchain_text_splitter
#!pip install langchain_chroma
#!pip install langchain_groq

# GROQ API KEY setting
import os
os.environ["GROQ_API_KEY"] = "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"

# Load the PDF from internet URL
import requests
url="http://gvpcew.ac.in/Material/IT/3%20IT%20Adv%20Java.pdf"
response=requests.get(url)

# Save the PDF in Local file
with open("java_collections.pdf", "wb") as f:
    f.write(response.content)

# Load the Unstructure PDF
#!pip install langchain_community

#!pip install unstructured
#!pip install "unstructured[pdf]"

from langchain_community.document_loaders import UnstructuredFileLoader
loader = UnstructuredFileLoader("java_collections.pdf")

#Split the document / chunks and load and split
#!pip install langchain_text_splitter
from langchain_text_splitters import CharacterTextSplitter
text_splitter = CharacterTextSplitter(
    chunk_size=2000,
    chunk_overlap=400
)
document = loader.load()
texts = text_splitter.split_documents(document)

type(texts)
len(texts)
texts[4]

from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings=HuggingFaceEmbeddings()

from langchain_chroma import Chroma
persist_directory = "vector_db"

vectordb = Chroma.from_documents(
    documents=texts,
    embedding=embeddings,
    persist_directory=persist_directory
)

# retriever vector to text
retriever = vectordb.as_retriever()

# llm from groq
from langchain_groq import ChatGroq
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

from langchain_classic.chains import RetrievalQA
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=True
)

# invoke the qa chain and get a response for user query
query = "get me the key of collection framework and count total how many key from this pdf "
response = qa_chain.invoke({"query": query})

print(response)

print(response["result"])